<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312214434 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, endpoint VARCHAR(255) NOT NULL, request_summary VARCHAR(500) DEFAULT NULL, response_summary VARCHAR(500) DEFAULT NULL, status_code INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_apilog_created ON api_logs (created_at)');
        $this->addSql('CREATE TABLE clients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id INT NOT NULL, surname VARCHAR(64) NOT NULL, name VARCHAR(64) NOT NULL, patronymic VARCHAR(64) DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, passport_series VARCHAR(10) DEFAULT NULL, passport_number VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_client_external_id ON clients (external_id)');
        $this->addSql('CREATE INDEX idx_client_fullname ON clients (surname, name, patronymic)');
        $this->addSql('CREATE TABLE pawn_good_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id INT DEFAULT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_13D36AFD9F75D7B0 ON pawn_good_categories (external_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_13D36AFD77153098 ON pawn_good_categories (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_13D36AFD5E237E06 ON pawn_good_categories (name)');
        $this->addSql('CREATE TABLE pawn_goods (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, estimated_value NUMERIC(10, 2) NOT NULL, good_type VARCHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pawn_ticket_number VARCHAR(10) NOT NULL, pawn_ticket_workplace_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D5E232A45DB9DC4B9BF5AA2 ON pawn_goods (pawn_ticket_number, pawn_ticket_workplace_id)');
        $this->addSql('CREATE INDEX IDX_1D5E232A12469DE2 ON pawn_goods (category_id)');
        $this->addSql('CREATE TABLE pawn_tickets (ticket_number VARCHAR(10) NOT NULL, external_id INT NOT NULL, status INT NOT NULL, issue_date DATE DEFAULT NULL, due_date DATE DEFAULT NULL, close_date DATE DEFAULT NULL, pledge_amount NUMERIC(10, 2) DEFAULT NULL, loan_amount NUMERIC(10, 2) DEFAULT NULL, interest_rate NUMERIC(5, 2) DEFAULT NULL, current_debt NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, workplace_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (ticket_number, workplace_id))');
        $this->addSql('CREATE INDEX IDX_BDD6954AC25FB46 ON pawn_tickets (workplace_id)');
        $this->addSql('CREATE INDEX IDX_BDD695419EB6921 ON pawn_tickets (client_id)');
        $this->addSql('CREATE INDEX idx_ticket_external_id ON pawn_tickets (external_id)');
        $this->addSql('CREATE INDEX idx_ticket_status ON pawn_tickets (status)');
        $this->addSql('CREATE INDEX idx_ticket_client_issue_date ON pawn_tickets (client_id, issue_date)');
        $this->addSql('CREATE INDEX idx_ticket_open_issue_date ON pawn_tickets (issue_date) WHERE status IN (2, 3, 4)');
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payment_type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pawn_ticket_number VARCHAR(10) NOT NULL, pawn_ticket_workplace_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B3245DB9DC4B9BF5AA2 ON payments (pawn_ticket_number, pawn_ticket_workplace_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, email VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE workplaces (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id INT NOT NULL, title VARCHAR(64) DEFAULT NULL, city VARCHAR(64) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C6CFBE69F75D7B0 ON workplaces (external_id)');
        $this->addSql('CREATE INDEX idx_workplace_external_id ON workplaces (external_id)');
        $this->addSql('CREATE INDEX idx_workplace_active ON workplaces (title, city) WHERE is_active = true');
        $this->addSql('ALTER TABLE pawn_goods ADD CONSTRAINT FK_1D5E232A45DB9DC4B9BF5AA2 FOREIGN KEY (pawn_ticket_number, pawn_ticket_workplace_id) REFERENCES pawn_tickets (ticket_number, workplace_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pawn_goods ADD CONSTRAINT FK_1D5E232A12469DE2 FOREIGN KEY (category_id) REFERENCES pawn_good_categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pawn_tickets ADD CONSTRAINT FK_BDD6954AC25FB46 FOREIGN KEY (workplace_id) REFERENCES workplaces (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pawn_tickets ADD CONSTRAINT FK_BDD695419EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B3245DB9DC4B9BF5AA2 FOREIGN KEY (pawn_ticket_number, pawn_ticket_workplace_id) REFERENCES pawn_tickets (ticket_number, workplace_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pawn_goods DROP CONSTRAINT FK_1D5E232A45DB9DC4B9BF5AA2');
        $this->addSql('ALTER TABLE pawn_goods DROP CONSTRAINT FK_1D5E232A12469DE2');
        $this->addSql('ALTER TABLE pawn_tickets DROP CONSTRAINT FK_BDD6954AC25FB46');
        $this->addSql('ALTER TABLE pawn_tickets DROP CONSTRAINT FK_BDD695419EB6921');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B3245DB9DC4B9BF5AA2');
        $this->addSql('DROP TABLE api_logs');
        $this->addSql('DROP TABLE clients');
        $this->addSql('DROP TABLE pawn_good_categories');
        $this->addSql('DROP TABLE pawn_goods');
        $this->addSql('DROP TABLE pawn_tickets');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE workplaces');
    }
}
